// atan2(I, Q) from the complex product -> delta phi
// arctg table:
/*
arctg(1) = pi/4
arctg(1/2) = 0.463648
arctg(1/4) = 0.244979
arctg(1/8) = 0.124355
arctg(1/16) = 0.062419
arctg(1/32) = 0.03124
arctg(1/64) = 0.015624
arctg(1/128) = 0.007812

script for generation is of the coordinates: fixed_point_arctg_table

rotation matrix:

A = [
    cos(theta)  -sin(theta);
    sin(theta)  cos(theta)
] = cos(theta) * [
    1           -tan(theta);
    tan(theta)  1
]

=> cos(theta) is omitted as it's not necessary
x_i = x_(i-1)           -/+ y_(i-1) * tan(t)
y_i = x_(i-1) * tan(t)  +/- y_(i-1)

*/
module atan2_cordic (
    input wire clk,
    input wire rst_n,

    // (x,y) vector to calculate angle for
    input wire signed [7:0] x_in, // signed int, has to fit I
    input wire signed [7:0] y_in, // signed int, has to fit Q
    input wire load_input, // HI when x/y should be updated and process should be started

    output wire angle_valid,
    output reg [11:0] angle_out // 2pi/4096 resolution = 0.0015339808 rad/bit, 4096 == 2pi
);
    reg [3:0] iteration_idx; // 0->9 (0 15): 0->7 - iteration

    reg signed [18:0] x_reg;
    reg signed [18:0] y_reg;

    reg [11:0] angle_table [0:7];

    assign angle_valid = (iteration_idx == 4'd8);

    wire positive_angle = (y_reg[18] == 1'b0);
    wire inverted_rotation = (x_reg[18] == 1'b1);

    // angles corresponding to the iteration (in angle_out format)
    // generated by fixed_point_arctg_table.py
    initial begin
        angle_table[0] = 12'd512;
        angle_table[1] = 12'd302;
        angle_table[2] = 12'd160;
        angle_table[3] = 12'd81;
        angle_table[4] = 12'd41;
        angle_table[5] = 12'd20;
        angle_table[6] = 12'd10;
        angle_table[7] = 12'd5;
    end

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            iteration_idx <= 4'd8;
            x_reg <= 19'd0;
            y_reg <= 19'd0;
            angle_out  <= 12'd0;
        end
        else begin
            if (load_input) begin
                // if coordinates are in 2nd or 3rd quadrant: move to 1st or 4th
                //x_reg[15:8] <= x_in[7] ? -x_in : x_in;
                //y_reg[15:8] <= x_in[7] ? -y_in : y_in;

                iteration_idx <= 4'd0; // restarts process

                x_reg <= {{11{x_in[7]}}, x_in} <<< 8;
                y_reg <= {{11{y_in[7]}}, y_in} <<< 8;

                angle_out <= x_in[7] ?
                    12'd2048 : // +pi if coordinates were rotated by pi (from quadrants 2 and 3)
                    12'd0;
            end
            else if (y_reg == 0) begin
                iteration_idx <= 4'd8; // finished
            end

            else if (!angle_valid) begin // last iteration not reached yet
                iteration_idx <= iteration_idx + 1;

                /*
                    x_i = x_(i-1)           -/+ y_(i-1) * tan(t)
                    y_i = x_(i-1) * tan(t)  +/- y_(i-1)
                */

                x_reg <= (positive_angle ~^ !inverted_rotation) ?
                    (x_reg + (y_reg >>> iteration_idx)) :
                    (x_reg - (y_reg >>> iteration_idx));

                y_reg <= (positive_angle ~^ !inverted_rotation) ?
                    (-(x_reg >>> iteration_idx)  + y_reg) :
                    ((x_reg >>> iteration_idx)   + y_reg);

                angle_out <= (positive_angle ~^ !inverted_rotation) ?
                    angle_out + angle_table[iteration_idx[2:0]] : // iteration_idx stays within 0 7 while iterating (3 bits). 8 means the cordic module is finished
                    angle_out - angle_table[iteration_idx[2:0]];
            end
        end
    end

endmodule


// increased input size atan2 module
module atan2_cordic_16b (
    input wire clk,
    input wire rst_n,
    input wire signed [15:0] x_in,
    input wire signed [15:0] y_in,
    input wire load_input,
    output wire angle_valid,
    output reg [11:0] angle_out
);
    reg [3:0] iteration_idx;
    reg signed [23:0] x_reg;
    reg signed [23:0] y_reg;
    reg [11:0] angle_table [0:7];

    assign angle_valid = (iteration_idx == 4'd8);

    wire positive_angle = (y_reg[23] == 1'b0);
    wire inverted_rotation = (x_reg[23] == 1'b1);

    initial begin
        angle_table[0] = 12'd512;
        angle_table[1] = 12'd302;
        angle_table[2] = 12'd160;
        angle_table[3] = 12'd81;
        angle_table[4] = 12'd41;
        angle_table[5] = 12'd20;
        angle_table[6] = 12'd10;
        angle_table[7] = 12'd5;
    end

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            iteration_idx <= 4'd8;
            x_reg <= 24'd0;
            y_reg <= 24'd0;
            angle_out <= 12'd0;
        end
        else begin
            if (load_input) begin
                x_reg <= {{8{x_in[15]}}, x_in} <<< 8;
                y_reg <= {{8{y_in[15]}}, y_in} <<< 8;
                iteration_idx <= 4'd0;
                angle_out <= x_in[15] ? 12'd2048 : 12'd0;
            end
            else if (y_reg == 0) begin
                iteration_idx <= 4'd8;
            end
            else if (!angle_valid) begin
                iteration_idx <= iteration_idx + 1;

                x_reg <= (positive_angle ~^ !inverted_rotation) ?
                    (x_reg + (y_reg >>> iteration_idx[2:0])) :
                    (x_reg - (y_reg >>> iteration_idx[2:0]));

                y_reg <= (positive_angle ~^ !inverted_rotation) ?
                    (-(x_reg >>> iteration_idx[2:0]) + y_reg) :
                    ((x_reg >>> iteration_idx[2:0]) + y_reg);

                angle_out <= (positive_angle ~^ !inverted_rotation) ?
                    angle_out + angle_table[iteration_idx[2:0]] :
                    angle_out - angle_table[iteration_idx[2:0]];
            end
        end
    end
endmodule



// ================ UNUSED MODULE ==================
/*
Input:
    - 2 pairs of I/Q coordinates
    - load_input

Output:
    - phase difference [0->2pi] -> [0 4096]

State defining variables
    - load_input (load input into phase_difference_calculator / start new run)
    - first_coordinates_loaded (have the first coordinates been loaded into atan2)
    - atan2_cordic_angle_valid (is the atan2 output currently valid)
    - busy (busy calculating phase difference)

States:
    - load_input LO: Not starting a new process
        - first_coordinates_loaded LO (Handling either second coordinates or nothing)
            - atan2_cordic_angle_valid LO:
                => Wait (atan2 idle or still processing)
            - atan2_cordic_angle_valid HI:
                => Has to have been handling second coordinates -> last step -> output
                @second_coordinates_finished
        - first_coordinates_loaded HI: (Handling first coordinates)
            - atan2_cordic_angle_valid LO:
                => Wait (atan2 idle or still processing)
            - atan2_cordic_angle_valid HI:
                => First coordinates finished -> 2nd pair can be loaded
                @load_second_coordinates

    - load_input HI: Starting a new process
        => Nothing else matters, load first pair of coordinates
        @load_input
*/
module phase_difference_calculator (
    input wire clk,
    input wire rst_n,

    input wire signed [7:0] I1,
    input wire signed [7:0] Q1,
    input wire signed [7:0] I2,
    input wire signed [7:0] Q2,

    input wire load_input,

    output reg [11:0] delta_phase_out,
    output reg delta_phase_valid
);
    reg [7:0] I2_reg;
    reg [7:0] Q2_reg;

    wire atan2_cordic_angle_valid;
    wire [11:0] atan2_cordic_angle_out;
    reg [11:0] phase1_reg;

    reg first_coordinates_loaded; // 0: i1/q1 not loaded yet, 1: i1/q1 loaded

    reg busy;

    // States (excluding load_input)
    wire load_second_coordinates = atan2_cordic_angle_valid & first_coordinates_loaded & !load_input;
    wire second_coordinates_finished = atan2_cordic_angle_valid & !first_coordinates_loaded & !load_input & busy;

    wire load_cordic_input = (load_input | load_second_coordinates);

    wire signed [7:0] atan2_cordic_x_in = load_second_coordinates ? (I2_reg) : (I1);
    wire signed [7:0] atan2_cordic_y_in = load_second_coordinates ? (Q2_reg) : (Q1);

    wire signed [11:0] phase_difference = atan2_cordic_angle_out - phase1_reg;

    atan2_cordic phase_atan2_cordic(
        .clk(clk),
        .rst_n(rst_n),
        .x_in(atan2_cordic_x_in),
        .y_in(atan2_cordic_y_in),
        .load_input(load_cordic_input),
        .angle_valid(atan2_cordic_angle_valid),
        .angle_out(atan2_cordic_angle_out)
    );

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            I2_reg <= 8'd0;
            Q2_reg <= 8'd0;
            phase1_reg <= 12'd0;
            first_coordinates_loaded <= 1'b0;
            delta_phase_out <= 12'd0;
            delta_phase_valid <= 1'b0;
            busy <= 1'b0;
        end

        else if (load_input) begin
            I2_reg <= I2;
            Q2_reg <= Q2;
            phase1_reg <= 12'd0;
            first_coordinates_loaded <= 1'b1;
            delta_phase_valid <= 1'b0;
            busy <= 1'b1;
        end
        else if (load_second_coordinates) begin
            phase1_reg <= atan2_cordic_angle_out;
            first_coordinates_loaded <= 1'b0;
            delta_phase_valid <= 1'b0;
        end
        else if (second_coordinates_finished) begin
            delta_phase_out <= phase_difference;
            first_coordinates_loaded <= 1'b0;
            delta_phase_valid <= 1'b1;
            busy <= 1'b0;
        end
    end
endmodule


/*
Converts phase difference to angle relative to the normal
The cases are generated by phase_to_angle_table.py
Angle of 0 means either centered target, or the phase was invalid
If the phase was invalid, invalid_input will be HI
*/
module phase_difference_to_angle (
    input wire clk,
    input wire rst_n,

    input wire [11:0] delta_phase_in,

    output reg [5:0] angle_out, // 64
    output reg invalid_input
);
    wire _unused_pd2a = &{1'b0, clk, rst_n, delta_phase_in[5:0]};

    always @(*) begin
        angle_out    = 6'd0;
        invalid_input = 1'b0;

        case (delta_phase_in[11:6])
            6'd0: angle_out = 6'd0;
            6'd1: angle_out = 6'd0;
            6'd2: angle_out = 6'd1;
            6'd3: angle_out = 6'd1;
            6'd4: angle_out = 6'd2;
            6'd5: angle_out = 6'd2;
            6'd6: angle_out = 6'd3;
            6'd7: angle_out = 6'd3;
            6'd8: angle_out = 6'd4;
            6'd9: angle_out = 6'd4;
            6'd10: angle_out = 6'd5;
            6'd11: angle_out = 6'd5;
            6'd12: angle_out = 6'd6;
            6'd13: angle_out = 6'd6;
            6'd14: angle_out = 6'd7;
            6'd15: angle_out = 6'd7;
            6'd16: angle_out = 6'd8;
            6'd17: angle_out = 6'd9;
            6'd18: angle_out = 6'd10;
            6'd19: angle_out = 6'd10;
            6'd20: angle_out = 6'd11;
            6'd21: angle_out = 6'd12;
            6'd22: angle_out = 6'd14;
            6'd42: angle_out = 6'd50;
            6'd43: angle_out = 6'd52;
            6'd44: angle_out = 6'd53;
            6'd45: angle_out = 6'd54;
            6'd46: angle_out = 6'd54;
            6'd47: angle_out = 6'd55;
            6'd48: angle_out = 6'd56;
            6'd49: angle_out = 6'd57;
            6'd50: angle_out = 6'd57;
            6'd51: angle_out = 6'd58;
            6'd52: angle_out = 6'd58;
            6'd53: angle_out = 6'd59;
            6'd54: angle_out = 6'd59;
            6'd55: angle_out = 6'd60;
            6'd56: angle_out = 6'd60;
            6'd57: angle_out = 6'd61;
            6'd58: angle_out = 6'd61;
            6'd59: angle_out = 6'd62;
            6'd60: angle_out = 6'd62;
            6'd61: angle_out = 6'd63;
            6'd62: angle_out = 6'd63;
            6'd63: angle_out = 6'd0;
            default: begin
                invalid_input = 1'b1;
            end
        endcase
    end
endmodule