// atan2(I, Q) from the complex product -> delta phi
// arctg table:
/*
arctg(1) = pi/4
arctg(1/2) = 0.463648
arctg(1/4) = 0.244979
arctg(1/8) = 0.124355
arctg(1/16) = 0.062419
arctg(1/32) = 0.03124
arctg(1/64) = 0.015624
arctg(1/128) = 0.007812

script for generation is of the coordinates: fixed_point_arctg_table

rotation matrix:

A = [
    cos(theta)  -sin(theta);
    sin(theta)  cos(theta)
] = cos(theta) * [
    1           -tan(theta);
    tan(theta)  1
]

=> cos(theta) is omitted as it's not necessary
x_i = x_(i-1)           -/+ y_(i-1) * tan(t)
y_i = x_(i-1) * tan(t)  +/- y_(i-1)

*/
module atan2_cordic (
    input wire clk,
    input wire rst_n,

    // (x,y) vector to calculate angle for
    input wire signed [7:0] x_in, // signed int, has to fit I
    input wire signed [7:0] y_in, // signed int, has to fit Q
    input wire load_input, // HI when x/y should be updated and process should be started

    output wire angle_valid,
    output reg [11:0] angle_out // 2pi/4096 resolution = 0.0015339808 rad/bit, 4096 == 2pi
);
    reg [3:0] iteration_idx; // 0->9 (0 15): 0->7 - iteration

    reg signed [18:0] x_reg;
    reg signed [18:0] y_reg;

    reg [11:0] angle_table [0:7];

    assign angle_valid = (iteration_idx == 4'd8);

    wire positive_angle = (y_reg[$high(y_reg)] == 1'b0);
    wire inverted_rotation = (x_reg[$high(x_reg)] == 1'b1);

    // angles corresponding to the iteration (in angle_out format)
    // generated by fixed_point_arctg_table.py
    initial begin
        angle_table[0] = 12'd512;
        angle_table[1] = 12'd302;
        angle_table[2] = 12'd160;
        angle_table[3] = 12'd81;
        angle_table[4] = 12'd41;
        angle_table[5] = 12'd20;
        angle_table[6] = 12'd10;
        angle_table[7] = 12'd5;
    end

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            iteration_idx <= 4'd8;
            x_reg <= '0;
            y_reg <= '0;
            angle_out  <= '0;
        end
        else begin
            if (load_input) begin
                // if coordinates are in 2nd or 3rd quadrant: move to 1st or 4th
                //x_reg[15:8] <= x_in[$high(x_in)] ? -x_in : x_in;
                //y_reg[15:8] <= x_in[$high(x_in)] ? -y_in : y_in;

                x_reg[7:0] <= '0;
                y_reg[7:0] <= '0;

                iteration_idx <= '0; // restarts process

                x_reg <= {{11{x_in[$high(x_in)]}}, x_in} <<< 8;
                y_reg <= {{11{y_in[$high(y_in)]}}, y_in} <<< 8;         

                angle_out <= x_in[$high(x_in)] ?
                    12'd2048 : // +pi if coordinates were rotated by pi (from quadrants 2 and 3)
                    '0;
            end 
            else if (y_reg == 0) begin
                iteration_idx <= 4'd8; // finished
            end 

            else if (!angle_valid) begin // last iteration not reached yet
                iteration_idx <= iteration_idx + 1;

                /*
                    x_i = x_(i-1)           -/+ y_(i-1) * tan(t)
                    y_i = x_(i-1) * tan(t)  +/- y_(i-1)
                */

                x_reg <= positive_angle ~^ !inverted_rotation ?
                    (x_reg + (y_reg >>> iteration_idx)) : 
                    (x_reg - (y_reg >>> iteration_idx));

                y_reg <= positive_angle ~^ !inverted_rotation ?
                    (-(x_reg >>> iteration_idx)  + y_reg) : 
                    ((x_reg >>> iteration_idx)   + y_reg);

                angle_out <= positive_angle ~^ !inverted_rotation ?
                    angle_out + angle_table[iteration_idx[2:0]] : // iteration_idx stays within 0 7 while iterating (3 bits). 8 means the cordic module is finished
                    angle_out - angle_table[iteration_idx[2:0]];
            end
        end
    end

endmodule

/*
Input:
    - 2 pairs of I/Q coordinates
    - load_input

Output:
    - phase difference [0->2pi] -> [0 4096]

State defining variables
    - load_input (load input into phase_difference_calculator / start new run)
    - first_coordinates_loaded (have the first coordinates been loaded into atan2)
    - atan2_cordic_angle_valid (is the atan2 output currently valid)
    - busy (busy calculating phase difference)

States:
    - load_input LO: Not starting a new process
        - first_coordinates_loaded LO (Handling either second coordinates or nothing)
            - atan2_cordic_angle_valid LO: 
                => Wait (atan2 idle or still processing)
            - atan2_cordic_angle_valid HI: 
                => Has to have been handling second coordinates -> last step -> output
                @second_coordinates_finished
        - first_coordinates_loaded HI: (Handling first coordinates)
            - atan2_cordic_angle_valid LO: 
                => Wait (atan2 idle or still processing)
            - atan2_cordic_angle_valid HI: 
                => First coordinates finished -> 2nd pair can be loaded
                @load_second_coordinates

    - load_input HI: Starting a new process
        => Nothing else matters, load first pair of coordinates
        @load_input
*/
module phase_difference_calculator (
    input wire clk,
    input wire rst_n,

    input wire signed [7:0] I1,
    input wire signed [7:0] Q1,
    input wire signed [7:0] I2,
    input wire signed [7:0] Q2,
    
    input wire load_input,

    output reg [11:0] delta_phase_out,
    output reg delta_phase_valid
);
    reg [7:0] I2_reg;
    reg [7:0] Q2_reg;

    wire atan2_cordic_angle_valid;
    wire [11:0] atan2_cordic_angle_out;
    reg [11:0] phase1_reg;

    reg first_coordinates_loaded; // 0: i1/q1 not loaded yet, 1: i1/q1 loaded

    reg busy;

    // States (excluding load_input)
    wire load_second_coordinates = atan2_cordic_angle_valid & first_coordinates_loaded & !load_input;
    wire second_coordinates_finished = atan2_cordic_angle_valid & !first_coordinates_loaded &! load_input & busy;

    wire load_cordic_input = (load_input | load_second_coordinates);

    wire signed [7:0] atan2_cordic_x_in = load_second_coordinates ? (I2_reg) : (I1);
    wire signed [7:0] atan2_cordic_y_in = load_second_coordinates ? (Q2_reg) : (Q1);

    wire signed [11:0] phase_difference = atan2_cordic_angle_out - phase1_reg;

    atan2_cordic phase_atan2_cordic(
        .clk(clk),
        .rst_n(rst_n),
        .x_in(atan2_cordic_x_in),
        .y_in(atan2_cordic_y_in),
        .load_input(load_cordic_input),
        .angle_valid(atan2_cordic_angle_valid),
        .angle_out(atan2_cordic_angle_out)
    );

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            I2_reg <= '0;
            Q2_reg <= '0;
            phase1_reg <= '0;
            first_coordinates_loaded <= 1'b0;
            delta_phase_out <= '0;
            delta_phase_valid <= 1'b0;
            busy <= 1'b0;
        end

        else if (load_input) begin
            I2_reg <= I2;
            Q2_reg <= Q2;
            phase1_reg <= '0;
            first_coordinates_loaded <= 1'b1;
            delta_phase_valid <= 1'b0;
            busy <= 1'b1;
        end
        else if (load_second_coordinates) begin
            phase1_reg <= atan2_cordic_angle_out;
            first_coordinates_loaded <= 1'b0;
            delta_phase_valid <= 1'b0;
        end
        else if (second_coordinates_finished) begin
            delta_phase_out <= phase_difference;
            first_coordinates_loaded <= 1'b0;
            delta_phase_valid <= 1'b1;
            busy <= 1'b0;
        end
    end
endmodule